stages:
  data_ingestion:
    cmd: python -m services.training.pipelines.training_pipeline --step ingestion
    deps:
      - services/training/pipelines/training_pipeline.py
      - services/training/data/data_ingestion.py
      - params.yaml
    params:
      - data_ingestion_params.test_size
      - data_ingestion_params.random_state
      - data_ingestion_params.shuffle
    outs:
      - artifacts/data/raw
      - artifacts/data/interim/train
      - artifacts/data/interim/test

  data_preprocessing:
    cmd: python -m services.training.pipelines.training_pipeline --step preprocess
    deps:
      - ./services/training/pipelines/training_pipeline.py
      - services/training/data/data_preprocessing.py
      - artifacts/data/interim/train
      - artifacts/data/interim/test
      - params.yaml
    params:
      - data_preprocessing_params.text_column_for_preprocessing
    outs:
      - artifacts/data/processed/preprocessed_training_data
      - artifacts/data/processed/preprocessed_test_data

  feature_engineering:
    cmd: python -m services.training.pipelines.training_pipeline --step fe
    deps:
      - ./services/training/pipelines/training_pipeline.py
      - services/training/features/feature_engineering.py
      - artifacts/data/processed/preprocessed_training_data
      - artifacts/data/processed/preprocessed_test_data
      - params.yaml
    params:
      - feature_engineering_params.text_column_for_engineering
      - TF-IDF_Params.max_df
      - TF-IDF_Params.min_df
      - TF-IDF_Params.max_features
      - TF-IDF_Params.ngram_range
    outs:
      - artifacts/data/feature_engineered/feature_engineered_training_data
      - artifacts/data/feature_engineered/feature_engineered_test_data
      - artifacts/saved_models/vectorizer

  model_training:
    cmd: python -m services.training.pipelines.training_pipeline --step train
    deps:
      - ./services/training/pipelines/training_pipeline.py
      - services/training/model/train_model.py
      - artifacts/data/feature_engineered/feature_engineered_training_data
      - params.yaml
    params:
      - Target_Col
      - Model_Params.C
      - Model_Params.penalty
      - Model_Params.solver
      - Model_Params.max_iter
      - Model_Params.tol
      - Model_Params.random_state
    outs:
      - artifacts/saved_models/model

  model_evaluation:
    cmd: python -m services.training.pipelines.training_pipeline --step evaluate
    deps:
      - ./services/training/pipelines/training_pipeline.py
      - services/training/model/evaluate_model.py
      - artifacts/data/feature_engineered/feature_engineered_test_data
      - params.yaml
    params:
      - Target_Col
    metrics:
      - artifacts/reports/performance_metrics.json

  model_registry:
    cmd: python -m services.training.pipelines.training_pipeline --step register
    deps:
      - ./services/training/pipelines/training_pipeline.py
      - services/training/model/register_model.py
      - artifacts/saved_models/model
      - artifacts/saved_models/vectorizer
      - artifacts/reports/performance_metrics.json
      - params.yaml