stages:
  data_ingestion:
    cmd: python -m services.training.pipelines.training_pipeline --step ingestion
    deps:
      - services/training/pipelines/training_pipeline.py
      - services/training/data/data_ingestion.py
      - params.yaml
    params:
      - data_ingestion.test_size
      - global_params.random_state
      - data_ingestion.shuffle
    outs:
      - artifacts/data/raw
      - artifacts/data/interim/train
      - artifacts/data/interim/test

  data_preprocessing:
    cmd: python -m services.training.pipelines.training_pipeline --step preprocess
    deps:
      - ./services/training/pipelines/training_pipeline.py
      - services/training/data/data_preprocessing.py
      - artifacts/data/interim/train
      - artifacts/data/interim/test
      - params.yaml
    params:
      - global_params.text_column
    outs:
      - artifacts/data/processed/preprocessed_training_data
      - artifacts/data/processed/preprocessed_test_data

  feature_engineering:
    cmd: python -m services.training.pipelines.training_pipeline --step fe
    deps:
      - ./services/training/pipelines/training_pipeline.py
      - services/training/features/feature_engineering.py
      - artifacts/data/processed/preprocessed_training_data
      - artifacts/data/processed/preprocessed_test_data
      - params.yaml
    params:
      - global_params.text_column
      - feature_engineering.tfidf
    outs:
      - artifacts/data/feature_engineered/feature_engineered_training_data
      - artifacts/data/feature_engineered/feature_engineered_test_data
      - artifacts/saved_models/vectorizer

  model_training:
    cmd: python -m services.training.pipelines.training_pipeline --step train
    deps:
      - ./services/training/pipelines/training_pipeline.py
      - services/training/model/train_model.py
      - artifacts/data/feature_engineered/feature_engineered_training_data
      - params.yaml
    params:
      - global_params.target_column
      - model_training.model_to_use
      - model_training.logistic_regression
      - model_training.lightgbm
    outs:
      - artifacts/saved_models/model

  model_evaluation:
    cmd: python -m services.training.pipelines.training_pipeline --step evaluate
    deps:
      - ./services/training/pipelines/training_pipeline.py
      - services/training/model/evaluate_model.py
      - artifacts/data/feature_engineered/feature_engineered_test_data
      - params.yaml
    params:
      - global_params.target_column
    metrics:
      - artifacts/reports/performance_metrics.json

  model_registry:
    cmd: python -m services.training.pipelines.training_pipeline --step register
    deps:
      - ./services/training/pipelines/training_pipeline.py
      - services/training/model/register_model.py
      - artifacts/saved_models/model
      - artifacts/saved_models/vectorizer
      - artifacts/reports/performance_metrics.json
      - params.yaml