### Data Ingestion ###
data_ingestion_params:
  test_size: 0.20
  random_state: 42
  shuffle: true

### Data Preprocessing ###
data_preprocessing_params:
  text_column_for_preprocessing: "review"

### Feature Engineering ###
feature_engineering_params:
  text_column_for_engineering: "review"

TF-IDF_Params:
  max_df: 0.9
  max_features: 10000
  min_df: 2
  ngram_range: [1,2] # Unigrams and Bigrams

### Model Training ###
Target_Col: "sentiment"

Model_Params:
  C: 0.1                # Inverse of regularization strength
  penalty: "l2"         # Regularization norm
  solver: "saga"        # Solver that supports elasticnet or l2
  max_iter: 300         # Maximum iterations for convergence
  tol: 0.001
  random_state: 42      # Seed for reproducibility

### Prediction Pipeline ###
prediction_pipeline_params:
  text_column_for_preprocessing: "review"
